# Семинар 2

- про Jupyter Notebook: https://devpractice.ru/python-lesson-6-work-in-jupyter-notebook/

## numpy

- документация: http://www.numpy.org/

Библиотека numpy является удобным инструментом для работы с многомерными массивами с возможностью векторизации вычислений. Рассмотрим базовые вещи, которые можно делать с помощью нее.

In [1]:
import numpy as np

In [2]:
vec = np.array([[1, 2], [3, 4], [5, 6]])

In [3]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
print(vec)

[[1 2]
 [3 4]
 [5 6]]


С чем мы работаем?

In [5]:
vec.dtype

dtype('int64')

In [6]:
type(vec)

numpy.ndarray

Размер массива:

In [7]:
vec.shape

(3, 2)

Число осей:

In [8]:
vec.ndim

2

У некоторых функций бывает параметр `axis`, который позволяет применить эту функцию по разным осям - в данном случае, по строкам или столбцам:

In [9]:
np.sum(vec)

21

In [10]:
np.sum(vec, axis=0)

array([ 9, 12])

In [11]:
np.sum(vec, axis=1)

array([ 3,  7, 11])

In [12]:
vec.sum()

21

Транспонируем массив:

In [16]:
vec.T

array([[1, 3, 5],
       [2, 4, 6]])

In [19]:
vec.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

Обратите внимание, что переменная `vec` не поменялась!

In [20]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

Размеры массивов можно менять:

In [21]:
vec.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
vec.reshape(-1, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
vec.reshape(2, -1)

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
vec.reshape(-1)

array([1, 2, 3, 4, 5, 6])

Индексирование:

In [25]:
vec[:, 1]

array([2, 4, 6])

In [26]:
vec[2, :]

array([5, 6])

In [27]:
vec[1:2, 0]

array([3])

In [28]:
vec[::2, :]

array([[1, 2],
       [5, 6]])

Булевы массивы:

In [29]:
is_even = vec % 2 == 0
print(is_even)

[[False  True]
 [False  True]
 [False  True]]


In [30]:
np.sum(is_even)

3

Булевы массивы позволяют вытаскивать элементы с True из массива того-же размера

In [31]:
vec[vec % 2 == 0]

array([2, 4, 6])

Иногда бывает полезно создавать специфичные массивы. Массив из нулей:

In [32]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

Массив из единиц:

In [33]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Единичная матрица:

In [34]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Массивы можно объединять:

In [35]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [36]:
np.hstack((vec, np.zeros(vec.shape)))

array([[1., 2., 0., 0.],
       [3., 4., 0., 0.],
       [5., 6., 0., 0.]])

In [37]:
np.vstack((vec, np.zeros(vec.shape)))

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

И, наконец - арифметические операции!

In [38]:
vec + 1

array([[2, 3],
       [4, 5],
       [6, 7]])

In [39]:
vec * 2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [40]:
vec ** 2

array([[ 1,  4],
       [ 9, 16],
       [25, 36]])

In [41]:
vec + vec ** 2

array([[ 2,  6],
       [12, 20],
       [30, 42]])

In [42]:
vec * vec ** 2

array([[  1,   8],
       [ 27,  64],
       [125, 216]])

In [43]:
np.sin(vec)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ]])

Матричное умножение:

In [44]:
vec.dot(vec ** 2)

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [45]:
vec.dot((vec ** 2).T)

array([[  9,  41,  97],
       [ 19,  91, 219],
       [ 29, 141, 341]])

In [47]:
vec @ (vec ** 2).T

array([[  9,  41,  97],
       [ 19,  91, 219],
       [ 29, 141, 341]])

In [48]:
vec * vec # поэлеметное, но не матричное умножение!

array([[ 1,  4],
       [ 9, 16],
       [25, 36]])

Broadcasting:
https://docs.scipy.org/doc/numpy-1.15.0/user/basics.broadcasting.html

In [49]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [50]:
np.arange(3)

array([0, 1, 2])

In [51]:
vec + np.arange(3)

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [52]:
np.arange(3).reshape(3, 1)

array([[0],
       [1],
       [2]])

In [53]:
vec + np.arange(3).reshape(3, 1)

array([[1, 2],
       [4, 5],
       [7, 8]])

Генерация случайных чисел:

In [60]:
np.random.rand(2, 3)

array([[0.24867403, 0.96945655, 0.73855123],
       [0.56139091, 0.72928931, 0.40668847]])

In [74]:
np.random.seed(3)
np.random.rand(2, 3)

array([[0.5507979 , 0.70814782, 0.29090474],
       [0.51082761, 0.89294695, 0.89629309]])

In [98]:
np.random.randn(3, 2)

array([[ 0.12800782,  1.24161652],
       [-0.7160258 ,  0.73146574],
       [ 0.42596675, -0.14901377]])

In [105]:
np.random.normal(2, 1, size=(3,2))

array([[0.51334193, 3.40862696],
       [0.9294145 , 2.37086997],
       [2.86283209, 1.35156798]])

In [117]:
np.random.randint(5, 10, size=3)

array([5, 8, 6])

Почему вообще используют `numpy`?

In [118]:
n = 300
A = np.random.rand(n, n)
B = np.random.rand(n, n)

In [119]:
%%time
C = np.zeros((n, n))
for i in range(n):
    for j in range(n):
        for k in range(n):
            C[i, j] += A[i, k] * B[k, j]

CPU times: user 20.9 s, sys: 24.2 ms, total: 21 s
Wall time: 21.1 s


In [122]:
%%time
C = A @ B

CPU times: user 3.25 ms, sys: 6.24 ms, total: 9.49 ms
Wall time: 2.13 ms


Операция присваивания

In [123]:
a = vec
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [124]:
vec[0,1] = 5
vec

array([[1, 5],
       [3, 4],
       [5, 6]])

In [125]:
a

array([[1, 5],
       [3, 4],
       [5, 6]])

In [126]:
b = vec.copy()

vec[2,1] = 10
vec

array([[ 1,  5],
       [ 3,  4],
       [ 5, 10]])

In [127]:
b

array([[1, 5],
       [3, 4],
       [5, 6]])

### Что ещё можно делать

Разворачивать массив

In [128]:
v = np.random.randint(5, 10, size=5)
v

array([5, 7, 7, 6, 7])

In [129]:
v[::-1]

array([7, 6, 7, 7, 5])

Читать информацию о функции

In [130]:
?np.random.randint

Перемешивать элементы массива

In [131]:
np.random.permutation(v)

array([5, 7, 6, 7, 7])

И многое другое...

### Задания для самостоятельного решения

1. Выведите квадраты первых десяти натуральных чисел

In [ ]:
#your code here

2. Выведите элементы массива, кратные трем.

In [ ]:
v = np.random.randint(5, 10, size=5)

#your code here

3. Найдите максимальный нечетный элемент в массиве.

In [ ]:
#your code here

4. Замените все нечетные элементы массива на ваше любимое число.

In [ ]:
#your code here

5. Создайте массив первых n нечетных чисел, записанных в порядке убывания. Например, если `n=5`, то ответом будет `array([9, 7, 5, 3, 1])`. *Функции, которые могут пригодиться при решении: `.arange()`*

In [ ]:
#your code here

6. Вычислите самое близкое и самое дальнее числа к данному в рассматриваемом массиве чисел. Например, если на вход поступают массив `array([0, 1, 2, 3, 4])` и число 1.33, то ответом будет `(1, 4)`. _Функции, которые могут пригодиться при решении: `.abs()`, `.argmax()`, `.argmin()`_

In [ ]:
#your code here

7*. Вычислите первообразную заданного полинома (в качестве константы возьмите ваше любимое число). Например, если на вход поступает массив коэффициентов `array([4, 6, 0, 1])`, что соответствует полиному $4x^3 + 6x^2 + 1$, на выходе получается массив коэффициентов `array([1, 2, 0, 1, -2])`, соответствующий полиному $x^4 + 2x^3 + x - 2$. _Функции, которые могут пригодиться при решении: `.append()`_

In [ ]:
#your code here

8*. Посчитайте первую производную для заданного полинома в заданной точке.

In [ ]:
#your code here